### PR TITLE
[release-0.26] [Channel] Set defaults of spec.delivery

### PR DESCRIPTION
**Pull request by pierDipi**
Backports:
- https://github.com/knative-sandbox/eventing-kafka/pull/990

### CODE REVIEW

**Comment by matzew** [comment]
Do we really need upstream  PR 933? or 949 ?  

None of that is used here

**Comment by matzew** [comment]
One more .... we had already #413  backport (which is upstream 957)
https://github.com/openshift-knative/eventing-kafka/blob/release-v0.26/pkg/apis/messaging/v1beta1/kafka_channel_validation.go#L87

**Comment by matzew** [comment]
For the defaults, can we "defaults" can we just get the merged SHA from 990 ? 


for https://github.com/knative-sandbox/eventing-kafka/pull/893  we do not directly need that (the operator is shipping) 
can we do that in a separate PR? and do the `make RELESAE......` thing ?

**Comment by pierDipi** [comment]
@matzew Done!

**Comment by pierDipi** [comment]
893 in https://github.com/openshift-knative/eventing-kafka/pull/444

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
@pierDipi can you rebase this? (and do the `make RELEASE` to be safe...?)

**Comment by pierDipi** [comment]
```
[pierdipi@pierdipi eventing-kafka]$ make RELEASE=v0.26.0 generate-release
./openshift/release/generate-release.sh v0.26.0
Writing resolved yaml to openshift/release/knative-eventing-kafka-source-ci.yaml
Writing resolved yaml to openshift/release/knative-eventing-kafka-channel-ci.yaml
Writing resolved yaml to openshift/release/knative-eventing-kafka-distributed-channel-ci.yaml
[pierdipi@pierdipi eventing-kafka]$ git status
On branch cp-895-v0.26-os
nothing to commit, working tree clean
```

**Pull request merged**
