### PR TITLE
[release-v0.21.0] Use dependencies instead of IMAGE_FORMAT 

### PR DESCRIPTION
**Pull request by devguyio**
- Switch to dependencies instead of IMAGE_FORMAT

based on  openshift/knative-eventing#1377

### CODE REVIEW

**Comment by mgencur** [comment]
In general, looks good.

The failure says:
```
openshift/e2e-common.sh: line 125: KNATIVE_EVENTING_KAFKA_CONSOLIDATED_CONTROLLER: unbound variable
```
So, this one needs to be passed on openshift/release side

**Comment by devguyio** [comment]
yep, those are the old job definitions so now let's hope the new ones will pass 🤞🏽

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
