### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by matzew** [comment]
When I run the `sed` to massage the manifests:

```
+ RELEASE_YAML=openshift/release/knative-eventing-kafka-channel-ci.yaml
+ sed -i -e 's|registry.ci.openshift.org/openshift/knative-.*:knative-eventing-kafka-consolidated-controller||g' openshift/release/knative-eventing-kafka-channel-ci.yaml
+ sed -i -e 's|registry.ci.openshift.org/openshift/knative-.*:knative-eventing-kafka-consolidated-dispatcher||g' openshift/release/knative-eventing-kafka-channel-ci.yaml
+ sed -i -e 's|registry.ci.openshift.org/openshift/knative-.*:knative-eventing-kafka-webhook||g' openshift/release/knative-eventing-kafka-channel-ci.yaml
+ cat openshift/release/knative-eventing-kafka-channel-ci.yaml
```

I do get this: 

```
diff --git a/openshift/release/knative-eventing-kafka-channel-ci.yaml b/openshift/release/knative-eventing-kafka-channel-ci.yaml
index 04b54568c..94f58946a 100644
--- a/openshift/release/knative-eventing-kafka-channel-ci.yaml
+++ b/openshift/release/knative-eventing-kafka-channel-ci.yaml
@@ -658,7 +658,7 @@ spec:
       serviceAccountName: kafka-ch-controller
       containers:
       - name: controller
-        image: registry.ci.openshift.org/openshift/knative-nightly:knative-eventing-kafka-consolidated-controller
+        image: 
         env:
         - name: CONFIG_LOGGING_NAME
           value: config-logging
```

which does explain errors like:
```
Error from server (Invalid): error when creating "STDIN": Deployment.apps "kafka-ch-controller" is invalid: spec.template.spec.containers[0].image: Required value
```

@mgencur is there something wrong with the `IMAGE_FORMAT` env var? 
https://github.com/openshift-knative/eventing-kafka/blob/main/openshift/e2e-common.sh#L108

**Comment by matzew** [comment]
/retest
:see_no_evil:

**Comment by devguyio** [comment]
/close
not needed, need #346 instead.

**Pull request closed without merging**
