### PR TITLE
upgrade to latest dependencies (#1127)

### PR DESCRIPTION
**Pull request by serverless-qe**
bumping knative.dev/control-protocol 79a0b1a...7e6cdf9:
  > 7e6cdf9 upgrade to latest dependencies (# 146)
  > b3c1e1b fix call to WaitUntilJobDone + update some dependencies  (# 148)
  > f22e1be Update community files (# 147)
  > 2c5188e Update actions (# 145)
bumping knative.dev/eventing f2045b0...9590bc3:
  > 9590bc3 adding min and max nodes annotation to rekt tests entrypoint (# 6243)
  > 4252411 Increase rekt test timings and reduce concurrency (# 6221)
  > 6fabdd5 Remove a second trigger of the autoscaler (# 6203)
  > 28a968c upgrade to latest dependencies (# 6230)
  > b349443 fixed links to source.md (# 6223)
  > f40fc74 Zero placements for rebalancing (# 6204)
  > 78aae1e Update community files (# 6220)
  > fdaca85 Update actions (# 6218)
  > 7ab1b0e upgrade to latest dependencies (# 6216)
bumping knative.dev/pkg fe26417...2fdd5f2:
  > 2fdd5f2 Update actions (# 2449)
  > 76a28b0 set git user name/email prior to merging upstream (# 2448)
bumping knative.dev/reconciler-test 2c3291f...84821d2:
  > 84821d2 Retry on context deadline exceeded errors (# 305)
  > d6d7c14 Update actions (# 291)
  > e2e54d1 Update community files (# 298)
  > 1b5d730 upgrade to latest dependencies (# 296)

Signed-off-by: Knative Automation <automation@knative.team>

### CODE REVIEW

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
