### PR TITLE
[release-v1.0] Reorganize generate ci config script

### PR DESCRIPTION
**Pull request by aliok**
Manual cherry pick of https://github.com/openshift-knative/eventing-kafka/pull/568

- There is one change from that cherry pick: no so-forward-compat test done in this branch.

@devguyio do we want it here too?

### CODE REVIEW

**Comment by aliok** [comment]
cc @pierDipi

**Review by pierDipi — APPROVED** [review]
/lgtm
/hold for the question to @devguyio

**Review by devguyio — APPROVED** [review]
/lgtm

**Pull request merged**
