### PR TITLE
[0.24] KafkaChannel to init offsets before dispatcher  (#886)

### PR DESCRIPTION
**Pull request by aliok**
Cherry pick 
- 3f2a9d72d40d0d7afe5037ca45313c1de7723dd6 of https://github.com/knative-sandbox/eventing-kafka/pull/886
- 15c5213cff88b3f507cefe2c5d4dbd4468628556 of https://github.com/knative-sandbox/eventing-kafka/pull/924

### CODE REVIEW

**Comment by aliok** [comment]
/test 47-e2e-aws-ocp-47

That's not good 😢 

```
TestChannelChain/KafkaChannel-messaging.knative.dev/v1beta1 (289.11s)
```

**Comment by matzew** [comment]
/test all (just to see what the 4.8 run gives us than again)

How about applying also https://github.com/knative-sandbox/eventing-kafka/pull/917/files  in here?

**Comment by matzew** [comment]
`ci/prow/48-e2e-aws-ocp-48` went green again... :monocle_face:

**Comment by matzew** [comment]
all green...

again:

/test all

**Comment by aliok** [comment]
/test all

all green. testing again.

**Comment by matzew** [comment]
and now the 4.8 falls off ...



/test 48-e2e-aws-ocp-48

For sure some sort of race/flake here, still

**Comment by matzew** [comment]
Green...

/test all

**Comment by matzew** [comment]
Green...again

Another round:
/test all

**Comment by aliok** [comment]
/test 48-e2e-aws-ocp-48
/test 48-e2e-aws-ocp-47

Both have
```
        Error: FAIL MATCHING: saw 1/2 matching events.
```

**Comment by matzew** [comment]
green...

/test 48-e2e-aws-ocp-48
/test 48-e2e-aws-ocp-47

**Pull request merged**
