### PR TITLE
[Backport][Release-v0.23] Support Eventing metrics

### PR DESCRIPTION
**Pull request by skonto**
Cherry picked https://github.com/openshift-knative/eventing-kafka/pull/234.

@slinkydeveloper afaik this is the right branch v0.23 and not v0.23.0 as discussed with @matzew, correct?

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@matzew can you double check we're using the right branch here?

**Comment by slinkydeveloper** [comment]
Will wait for matzew approval

/lgtm

**Comment by skonto** [comment]
@matzew gentle ping.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
