### PR TITLE
[release-v1.1] Adding dry-run to tweak secret creation, if already present

### PR DESCRIPTION
**Pull request by ReToCode**
Port https://github.com/openshift-knative/eventing-kafka/pull/673 to script in `openshift` folder.

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
Thanks!

/lgtm
/approve

**Comment by aliok** [comment]
FORCE MERGE! FORCE MERGE! FORCE MERGE!

**Comment by ReToCode** [comment]
Force-Merging. Images successfully built, test failures are not related to the changes.

**Comment by matzew** [comment]
The good news is: this branch is less or more not used, except for a few tests (we need to migrate them).

**Pull request merged**
