### PR TITLE
Skip tests for source

### PR DESCRIPTION
**Pull request by matzew**
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1391/pull-ci-openshift-knative-serverless-operator-main-4.9-upstream-e2e-aws-ocp-49/1495747353007624192/build-log.txt

* Test for `KafkaBinding` are no longer supported - we do not ship that anymore w/ 1.1 (Serverless 1.22)
* SourceClaims and Reconciler tests are failing on the downstream with the new source

### CODE REVIEW

**Comment by matzew** [comment]
Worth to look at running the actual e2e tests from https://github.com/knative-sandbox/eventing-kafka-broker/tree/main/test/e2e

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

/retest

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
