### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by matzew** [comment]
```
error: error copying source path /go/bin/migrate to .: exit status 1
```

something wrong with the migrator binaries, @devguyio

**Comment by matzew** [comment]
I think in the `install` Make target, we need:

```
	go build -o $(GOPATH)/bin/migrate $(MIGRATE_IMAGE)
```

Or. we move the image to the "core" images, similar to what we have in the https://github.com/openshift/knative-eventing/blob/main/Makefile#L5

Or as we had it here before:
https://github.com/openshift-knative/eventing-kafka/pull/195

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
