### PR TITLE
Update community files (#1040)

### PR DESCRIPTION
**Pull request by serverless-qe**
Signed-off-by: Knative Automation <automation@knative.team>

### CODE REVIEW

**Comment by pierDipi** [comment]
https://github.com/knative-sandbox/reconciler-test/pull/283/files

**Comment by pierDipi** [comment]
https://github.com/knative/eventing/pull/6056

**Comment by pierDipi** [comment]
We need some more information: https://github.com/knative/eventing/pull/6056/files

**Comment by aliok** [comment]
```
{
  "kind": "Trigger",
  "apiVersion": "eventing.knative.dev/v1",
  "metadata": {
    "name": "trigger",
    "namespace": "eventing-e2e3",
    "uid": "cf44d22e-55e8-401b-b852-45368ec32ff8",
    ...
    "labels": {
      "eventing.knative.dev/broker": "kafkachannel"
    },
    "annotations": {
      "eventing.knative.dev/creator": "system:admin",
      "eventing.knative.dev/lastModifier": "system:admin"
    },
  },
  "status": {
    "observedGeneration": 1,
    "conditions": [
      {
        "type": "Ready",
        "status": "False",
        "lastTransitionTime": "2022-01-20T01:08:35Z",
        "reason": "ChannelTemplateFailed",
        "message": "Error on setting up the ChannelTemplate: not found"
      },
      ...
    ]
  }
}
```

**Comment by aliok** [comment]
I now understand why this fails.

Our code here creates the broker configmap like this:
```
apiVersion: v1
data:
  channel-template-spec: |-
    apiVersion: "messaging.knative.dev/v1beta1"
    kind: "KafkaChannel"
kind: ConfigMap
```

However, the core Knative Eventing code, specifically the `mt-broker-controller` is still using the previous key: `channelTemplateSpec`. This is changed here: https://github.com/knative/eventing/pull/5875/files#diff-73079bce11644fbc35a138c5591b54e36d56db80609d64a4cc1599de1395dd5eL47-L50

In the end, we get this error:

```
"caller": "broker/config.go:49",
"msg": "ConfigMap is missing key",
```

We need to make these CI jobs install the latest version of core Knative Eventing.

The change done is backwards compatible. That's not the issue here. The issue is that the previous code isn't "forwards-compatible" :trollface:

**Comment by matzew** [comment]
IMO we should keep the installation via the product, like here: 
https://github.com/openshift-knative/eventing-kafka/blob/main/openshift/e2e-common.sh#L103

I'd vote against intsalling Eventing core here directly - if we can avoid it 

That said: temporary it is OK. (and we had that before)... we could apply these two:
* https://github.com/openshift/knative-eventing/blob/release-next/openshift/release/knative-eventing-ci.yaml
* https://github.com/openshift/knative-eventing/blob/release-next/openshift/release/knative-eventing-mtbroker-ci.yaml

and set the `InSTALL_EVENTING` to false, like here: https://github.com/openshift/knative-eventing/blob/release-next/openshift/e2e-common.sh#L159

**Comment by matzew** [comment]
> The change done is backwards compatible. That's not the issue here. The issue is that the previous code isn't "forwards-compatible" :trollface:

Let's double check if this has impact on product. Do we have a JIRA to properly release note this? Let's plesae double check this - thanks!

**Comment by aliok** [comment]
One option to fix it can be also setting the previous key with the same value here: https://github.com/knative/eventing/blob/6f1ed337c3c51c7e52dcb91cc3ff881812b75bc5/test/lib/creation.go#L174

Would it affect OpenShift Serverless users? 
* Since the key change is done in a backwards compatible way, they can still continue using the old key, which they would have in their configmap which is referenced in Broker configmap.
* The only possible scenario that this fails is they start using the to new key, before we ship our code that uses the new (and the old) key. We should document this I think with something like this: "In most recent recent versions of Knative Eventing, MT Broker channel template is specified with a new key in the configmaps for the created Brokers. At OpenShift Serverless the new key is not used yet."

**Comment by devguyio** [comment]
```
the build knative-eventing-kafka-consolidated-controller failed after 1s with reason GenericBuildFailed: Generic Build failure - check logs for details. | the build knative-eventing-kafka-consolidated-controller failed after 1s with reason GenericBuildFailed: Generic Build failure - check logs for details.
-- | --
the build knative-eventing-kafka-consolidated-controller failed after 1s with reason GenericBuildFailed: Generic Build failure - check logs for details.
 ```
/retest

**Pull request merged**
