### PR TITLE
[v0.20.0] Backport of Update target pod IPs when dispatcher pods scale (knative-sandbox/eventing-kafka#496)

### PR DESCRIPTION
**Pull request by devguyio**
Backport of Update target pod IPs when dispatcher pods scale (knative-sandbox/eventing-kafka#496)

### CODE REVIEW

**Comment by matzew** [comment]
rebased :see_no_evil:  ... after https://github.com/openshift-knative/eventing-kafka/pull/135  

:pray:

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
