### PR TITLE
[release-v0.25] Adding 4.9 for ci generator

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

as per title

### CODE REVIEW

**Comment by matzew** [comment]
/hold
(for now)

**Comment by devguyio** [comment]
@matzew I take it we don't wanna use cluster pools for 4.9?

**Comment by matzew** [comment]
@devguyio yeah, I updated the script genrator, and also updated the https://github.com/openshift/release/pull/22295 PR

**Pull request merged**
